# Starter pipeline

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false


- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'finallabdevsecops'
    scannerMode: 'MSBuild'
    projectKey: 'FinalLabDevSecOps_spring-boot-kubernetes'
    projectName: 'FinalLabDevSecOps'